#!/bin/bash

zip_filename=instacart-pp-$(whoami).zip
pwd=$(pwd)


echo "-- cleaning build files"
./gradlew clean

echo "-- zipping project"
zip -r $pwd/../$zip_filename $pwd/*

echo "-- project zipped to ${pwd/../$zip_filename}"
